apiVersion: v1
kind: Service
metadata:
  name: my-svc-mysql
  labels:
    name: mysql5
spec:
  type: ClusterIP
  ports:
  - name: my-clusterip-mysql
    port: 3306
    targetPort: 3306
  selector:
    app: mysql  # 앞서 만든 pod 의 (key,value) pair
